# Used to specific environment specific behavior
# local - pretty text logging
# stage - none
# prod - none
Environment: "local"
Log:
  Level: "debug"

Router:
  TimeoutSec: 10
  RequestPerSecLimit: 5
  DisableCors: false
  AllowedOrigins:
    - "https://*.quibbble.com"
    - "http://127.0.0.1:*"
    - "http://localhost:*"
  AllowedMethods:
    - "GET"
    - "POST"
  AllowedHeaders:
    - "Origin"
    - "Content-Type"
    - "Accept"

Server:
  Port: "8080"

Network:
  Games:
    - "Carcassonne"
    - "Connect4"
    - "Tsuro"
    - "Stratego"
    - "XAlpha"
    # - "Tic-Tac-Toe"
    # - "Codenames"
  Adapters:
  GameExpiry: "1h"
