# Used to specific environment specific behavior
# local - pretty text logging
# stage - none
# prod - none
Environment: "local"
Log:
  Level: "debug"

Router:
  TimeoutSec: 10
  RequestPerSecLimit: 1000
  DisableCors: false
  AllowedOrigins:
    - "https://*.quibbble.com"
    - "http://127.0.0.1:3000"
  AllowedMethods:
    - "GET"
    - "POST"
  AllowedHeaders:
    - "Origin"
    - "Content-Type"
    - "Accept"

Server:
  Port: "8080"

Network:
  Games:
    - "Tic-Tac-Toe"
    - "Carcassonne"
    - "Connect4"
    - "Codenames"
    - "Tsuro"
  Adapters:
  GameExpiry: "3h"
