# Used to specific environment specific behavior
# local - pretty text logging
# stage - none
# prod - none
Environment: "local"
Log:
  Level: "debug"

Router:
  TimeoutSec: 10
  RequestPerSecLimit: 5
  DisableCors: false
  AllowedOrigins:
    - "http://127.0.0.1:*"
    - "http://localhost:*"
  AllowedMethods:
    - "GET"
    - "POST"
  AllowedHeaders:
    - "Origin"
    - "Content-Type"
    - "Accept"

Server:
  Port: "8080"

Network:
  Games:
    - "Carcassonne"
    - "Codenames"
    - "Connect4"
    - "Indigo"
    - "Stratego"
    - "Tic-Tac-Toe"
    - "Tsuro"
  GameExpiry: "3h"

Datastore:
  Redis:
    Enabled: false         
    Host: <REDIS_HOST>
    Password: <REDIS_PASSWORD>
