name: 'Docker Image CI'

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:

  build:

    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        token_format: 'access_token'
        workload_identity_provider: 'projects/405124156249/locations/global/workloadIdentityPools/gh-pool/providers/gh-provider'
        service_account: 'gh-machine-user@quibbble-7236c.iam.gserviceaccount.com'

    - name: 'Login to Google Artifact Registry'
      uses: 'docker/login-action@v2'
      with:
        registry: 'us-west1-docker.pkg.dev'
        username: 'oauth2accesstoken'
        password: '${{ steps.auth.outputs.access_token }}'

    - name: 'Set Docker Image Tag ENV'
      run: 'echo "DOCKER_IMAGE_TAG=us-west1-docker.pkg.dev/quibbble-7236c/quibbble/quibbble:${GITHUB_REF#refs/*/}" >> $GITHUB_ENV'

    - name: 'Build the Docker Image'
      run: 'docker build --tag ${DOCKER_IMAGE_TAG} --platform linux/amd64 -f build/Dockerfile .'

    - name: 'Push the Docker Image'
      run: 'docker push ${DOCKER_IMAGE_TAG}'
